// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVeBQZummwccCbHqG7YdbK6AWgK3wTnHs',
    appId: '1:294139838869:web:a6fe6b8e6df496632ef69c',
    messagingSenderId: '294139838869',
    projectId: 'study-app-8ec6d',
    authDomain: 'study-app-8ec6d.firebaseapp.com',
    storageBucket: 'study-app-8ec6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOe39TTpTVPCGQFxGCg2uaIyc7uWW3lUo',
    appId: '1:294139838869:android:457a6aa38699092f2ef69c',
    messagingSenderId: '294139838869',
    projectId: 'study-app-8ec6d',
    storageBucket: 'study-app-8ec6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8F-XdLuHQKB8Edq6hD02OCYrSeyMa4Gg',
    appId: '1:294139838869:ios:b5e33dd12a972b332ef69c',
    messagingSenderId: '294139838869',
    projectId: 'study-app-8ec6d',
    storageBucket: 'study-app-8ec6d.appspot.com',
    iosClientId: '294139838869-s401ft93c5d7ttfg7rg7l5o2cc1rv7jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8F-XdLuHQKB8Edq6hD02OCYrSeyMa4Gg',
    appId: '1:294139838869:ios:aa1c2a20c8c520ea2ef69c',
    messagingSenderId: '294139838869',
    projectId: 'study-app-8ec6d',
    storageBucket: 'study-app-8ec6d.appspot.com',
    iosClientId: '294139838869-9lo6ath7bvlaorsf76et105kfjb9m664.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp.RunnerTests',
  );
}
